name: pomodoro
description: A sleek pomodo app.

publish_to: 'Play Store' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vibration: ^3.1.3
  provider: ^6.1.5+1
  screen_brightness: ^2.1.7
  audioplayers: ^6.5.1
  shared_preferences: ^2.5.3
  wakelock_plus: ^1.4.0
  flutter_native_splash: ^2.4.6
  path_provider: ^2.1.5
  sliding_clipped_nav_bar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/audio/finish.mp3

  fonts:
    - family: Sofia
      fonts:
        - asset: fonts/Sofia-Thin.ttf
          weight: 100
        - asset: fonts/Sofia-ExtraLight.ttf
          weight: 200
        - asset: fonts/Sofia-Light.ttf
          weight: 300
        - asset: fonts/Sofia-Regular.ttf
          weight: 400
        - asset: fonts/Sofia-Medium.ttf
          weight: 500
        - asset: fonts/Sofia-SemiBold.ttf
          weight: 600
        - asset: fonts/Sofia-Bold.ttf
          weight: 700
        - asset: fonts/Sofia-ExtraBold.ttf
          weight: 800
        - asset: fonts/Sofia-Black.ttf
          weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
